backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: assets

display_url: https://futuresfinefurniture.netlify.com

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name : blog
    label : Blog
    folder : collections/blog
    create : true
    slug: "{{year}}-{{slug}}"
    fields :
      - { name: "title", label: "Title", }
      - { name: "thumbnail", label: "Featured Image", widget: "image", required: false, }
      - { name: "body", label: "Body", widget: "markdown", }
  - name : productCategories
    label : Product Categories
    folder : collections/productCats
    create : true
    fields : 
      - { name: "title", label: "Title", }
      - { name: "body", label: "Body", widget: "markdown"}
      - { name: "images", label: "Featured Images", widget: "list", required: false, field:  { label: Image, name: image, widget: image}}
      - { name: "enabled", label: "enabled", widget: "boolean", default: true, hint: "this will disable all products within this category"}
  - name : productRange
    label: Product Range
    folder : collections/productRange
    create: true
    fields : 
      - { name: "title", label: "Title", }
      - { name: "body", label: "Body", widget: "markdown"}
      - { name: "enabled", label: "Enabled", widget: "boolean", default: true, hint: "this will enable all products within the range"}
  - name : product
    label: Product
    folder : collections/product
    create: true
    fields :
      - { name: "title", label: "Title"}
      - { name: "body", label: "Body", widget: "markdown"}
      - { name: "enabled", label: "Enabled", widget: "boolean", default: true, hint: "this will enabled the product"}
      - { name: "Category", label: "Category", widget: "relation", collection: "productCategories", searchFields:["title"], valueField: "title", displayFields: ["title", "enabled"]}
      - { name: "range", label: "Range", required: False, widget: "relation", collection: "productRange", searchFields: ["title","enabled"], valueField: "title", displayFields: ["title", "enabled"]}
      - name: "images"
        label: "images"
        required: False
        widget: "list"
        field: {label: Image, name: image, widget: image}
      - name: "variants"
        label: "Variant"
        widget: "list"
        fields:
          - { name: "sku", label: "sku" }
          - { name: "price", label: "Price", widget: number, valueType: 'int' }
          - { name: "Name", label: "Name"}
          - name: "properties"
            label: "Properties"
            widget: "list"
            fields:
              - { label: propertyType, name: propertyType, widget: "select", options: ['size', 'material','colour','dimentions','weight']}
              - { label: propertyValue, name: propertyValue, widget: "string"}