---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: "\\collections\\productCats"
  label: category
  create: documents
  match: "**/*"
  templates:
  - category
- type: directory
  path: "\\collections\\product"
  label: products
  create: documents
  match: "**/*"
  templates:
  - product
upload_dir: "\\static\\images\\uploads"
public_path: public\images\uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gatsby build
  publish_command: gatsby build
  preview_output_directory: public
  output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
