---
label: product
hide_body: false
fields:
- type: text
  name: title
  label: title
- name: disabled
  type: boolean
  label: disabled
- type: text
  name: Category
  label: Category
- type: text
  name: range
  label: range
- type: image_gallery
  name: images
  label: images
- type: field_group_list
  name: variants
  label: variants
  fields:
  - type: number
    name: price
    label: price
  - type: text
    name: variantName
    label: variantName
  - name: disabled
    type: boolean
    label: disabled
    description: this will disable this variant
  - name: discount
    type: number
    label: discount
    description: discount in cents
    default: 0
    required: true
    config:
      min: 
      max: 
      step: 
