---
label: product
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: title
- name: category
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: category
      file: 
      path: 
  label: category
