---
label: product
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: title
- name: category
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: category
      file: 
      path: 
  label: Category
- name: created
  type: datetime
  label: created
  description: ''
  config:
    required: false
    date_format: ''
    time_format: 
    display_utc: false
    export_format: YYYY-MM-DD
- name: updated
  type: datetime
  label: updated
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
    export_format: YYYY-MM-DD
- name: disabled
  type: boolean
  label: disabled
- type: text
  name: range
  label: range
- type: image_gallery
  name: images
  label: images
- type: field_group_list
  name: variants
  label: variants
  fields:
  - type: text
    name: variantName
    label: variantName
  - type: number
    name: price
    label: price
    config:
      step: '1'
  - name: disabled
    type: boolean
    label: disabled
    description: this will disable this variant
  - name: discount
    type: number
    label: discount
    description: discount in cents
    default: 0
    required: true
    config:
      min: 
      max: 
      step: 
pages:
- collections/product/testproduct.md
